# Build x2t converter from pre-compiled artifacts
name: X2T

on:
  push:
    path-ignore:
      - 'README.md'

  pull_request:
    branches:
      - 'as_master'

jobs:

  build:
    name: ${{ matrix.osname }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name:
          - ubuntu-16.04
          - macOS-latest

        include:
          - name: ubuntu-16.04
            os: ubuntu-16.04
            osname: Linux
            build_target: linux_64

          - name: macOS-latest
            os: macOS-latest
            osname: macOS
            build_target: mac_64

    steps:
      - uses: actions/checkout@v1

      - name: Setup external projects
        run: |
          cd $GITHUB_WORKSPACE/..
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/airslateinc/onlyoffice-sdkjs.git
          git clone https://github.com/ONLYOFFICE/core-fonts.git

      - name: Fetch build artifacts
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JFROG_INFRA_CONFIG }}
        run: |
          [ -d "./.artifactory/${{ runner.build_target }}" ] || mkdir -p ./.artifactory/${{ runner.build_target }}
          jfrog --version
          jfrog rt dl onlyoffice-core/core/${{ runner.build_target }}/latest/core_builds.zip ./.artifactory

      - name: Assemble X2T converter
        run: |
          cd ./X2tConverter
          make -f x2tConverter.mk
          make -f x2tConverter.mk sdkjs sdkjs-branch=ovm_fillable_fields
